---
- name: Customize Jumpstart Installation
  hosts: system
  gather_facts: no
  

  vars_prompt:
    - name: js_understand_default
      prompt: "We will now go through Command Line Tools..."
      default: "ok"
      private: no
    - name: js_homebrewpackage_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_zshtheme_spaceship_enabled
      prompt: "Would you like to set the Zsh theme to spaceship?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_python_enabled
      prompt: "Would you like to install Python?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_git_enabled
      prompt: "Would you like to install Git?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_node_enabled
      prompt: "Would you like to install NodeJS?"
      default: "yes"
      private: no
    - name: js_understand_default
      prompt: "We will now go through General Applications and Tools..."
      default: "ok"
      private: no
    - name: js_homebrewcask_googlechrome_enabled
      prompt: "Would you like to Install Google Chrome?"
      default: "yes"
      private: no
    - name: js_homebrewcask_iterm2_enabled
      prompt: "Would you like to install iTerm2?"
      default: "yes"
      private: no
    - name: js_homebrewcask_sublimetext3_enabled
      prompt: "Would you like to install Sublime Text 3?"
      default: "yes"
      private: no
    - name: js_homebrewcask_atom_enabled
      prompt: "Would you like to install Atom?"
      default: "yes"
      private: no
    - name: js_homebrewcask_visualstudiocode_enabled
      prompt: "Would you like to install Visual Studio Code?"
      default: "yes"
      private: no
    - name: js_homebrewcask_gpgsuite_enabled
      prompt: "Would you like to install GPG Suite?"
      default: "yes"
      private: no
    - name: js_homebrewcask_slack_enabled
      prompt: "Would you like to install Slack?"
      default: "yes"
      private: no
    - name: js_homebrewcask_discord_enabled
      prompt: "Would you like to install Discord?"
      default: "yes"
      private: no
    - name: js_homebrewcask_mactex_enabled
      prompt: "Would you like to install MacTex?"
      default: "yes"
      private: no
    - name: js_homebrewcask_docker_enabled
      prompt: "Would you like to install Docker?"
      default: "yes"
      private: no
    - name: js_homebrewcask_java_enabled
      prompt: "Would you like to install Java?"
      default: "yes"
      private: no

  tasks:
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zsh_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zsh_enabled: {{ js_homebrewpackage_zsh_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zshtheme_spaceship_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zshtheme_spaceship_enabled: {{ js_homebrewpackage_zshtheme_spaceship_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_python_enabled: (?:True|False)$"
        line: "js_homebrewpackage_python_enabled: {{ js_homebrewpackage_python_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_git_enabled: (?:True|False)$"
        line: "js_homebrewpackage_git_enabled: {{ js_homebrewpackage_git_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_node_enabled: (?:True|False)$"
        line: "js_homebrewpackage_node_enabled: {{ js_homebrewpackage_node_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_googlechrome_enabled: (?:True|False)$"
        line: "js_homebrewcask_googlechrome_enabled: {{ js_homebrewcask_googlechrome_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_iterm2_enabled: (?:True|False)$"
        line: "js_homebrewcask_iterm2_enabled: {{ js_homebrewcask_iterm2_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_sublimetext3_enabled: (?:True|False)$"
        line: "js_homebrewcask_sublimetext3_enabled: {{ js_homebrewcask_sublimetext3_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_atom_enabled: (?:True|False)$"
        line: "js_homebrewcask_atom_enabled: {{ js_homebrewcask_atom_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_visualstudiocode_enabled: (?:True|False)$"
        line: "js_homebrewcask_visualstudiocode_enabled: {{ js_homebrewcask_visualstudiocode_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_gpgsuite_enabled: (?:True|False)$"
        line: "js_homebrewcask_gpgsuite_enabled: {{ js_homebrewcask_gpgsuite_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_slack_enabled: (?:True|False)$"
        line: "js_homebrewcask_slack_enabled: {{ js_homebrewcask_slack_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_discord_enabled: (?:True|False)$"
        line: "js_homebrewcask_discord_enabled: {{ js_homebrewcask_discord_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_mactex_enabled: (?:True|False)$"
        line: "js_homebrewcask_mactex_enabled: {{ js_homebrewcask_mactex_enabled|bool }}"  
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_docker_enabled: (?:True|False)$"
        line: "js_homebrewcask_docker_enabled: {{ js_homebrewcask_docker_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_java_enabled: (?:True|False)$"
        line: "js_homebrewcask_java_enabled: {{ js_homebrewcask_java_enabled|bool }}"